# Generated by Django 3.2.16 on 2023-04-11 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_pair',
        ),
    ]
